# Generated by Django 5.2.6 on 2025-09-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('turma', models.CharField(blank=True, max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('descritor', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='escola.aluno')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='escola.conteudo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='escola.professor')),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['inicio'], name='escola_agen_inicio_a7c5a8_idx'), models.Index(fields=['status'], name='escola_agen_status_6508de_idx'), models.Index(fields=['professor', 'inicio'], name='escola_agen_profess_c8bdb8_idx')],
            },
        ),
    ]
