# Generated by Django 5.2.6 on 2025-09-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='descritor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
