# Generated by Django 5.2.7 on 2025-10-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_conteudo_descritor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-inicio'], 'permissions': [('view_relatorio', 'Pode visualizar relatórios'), ('export_relatorio', 'Pode exportar relatórios')]},
        ),
    ]
