# Generated by Django 5.2.7 on 2025-10-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_agendamento_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='turma',
            new_name='turno',
        ),
    ]
