# Generated by Django 5.2.7 on 2025-11-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_rename_turma_aluno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
